title: "Rose K. Cersonsky"
email: rosecers@umich.edu
email: rose.cersonsky@epfl.ch
twitter: "@rosycers"
logo: /assets/gallery/logo.png

theme: jekyll-theme-minimal
markdown: kramdown

# Build settings
plugins:
  - jekyll-seo-tag

defaults:
  #_features
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
