title: "Rose K. Cersonsky"
email: rosecers@umich.edu
email: rose.cersonsky@epfl.ch
twitter: "@rosycers"
logo: /assets/gallery/logo.jpeg

theme: jekyll-theme-minimal
markdown: kramdown

# Build settings
url: "http://rosecers.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  #_features
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
